// Generated by Antigravity Auto-Accept VS Code Plugin
const fs = require('fs');
const path = require('path');

let inputData = '';
process.stdin.setEncoding('utf8');

process.stdin.on('data', chunk => {
    inputData += chunk;
});

process.stdin.on('end', () => {
    try {
        const payload = JSON.parse(inputData || '{}');
        const toolCall = payload.toolCall || {};
        const toolName = toolCall.name || '';
        const args = toolCall.args || {};
        const commandLine = args.CommandLine || args.command || args.url || '';

        const configPath = path.join(__dirname, 'autoaccept-config.json');
        let settings = { enabled: true, types: { consoleCommands: true, scriptExecution: false, webViews: true, fileEdits: true } };

        if (fs.existsSync(configPath)) {
            settings = JSON.parse(fs.readFileSync(configPath, 'utf8'));
        }

        if (!settings.enabled) {
            console.log(JSON.stringify({ decision: 'ask', reason: 'Auto-accept is disabled.' }));
            return;
        }

        // Safety denylist check
        const denylist = settings.denylist || [];
        const fullText = (toolName + ' ' + commandLine).trim();
        for (const pattern of denylist) {
            try {
                if (new RegExp(pattern, 'i').test(fullText)) {
                    console.log(JSON.stringify({ decision: 'force_ask', reason: 'Matched safety denylist: ' + pattern }));
                    return;
                }
            } catch (_) {}
        }

        // Determine category
        const isWeb = /(read_browser_page|browser_|open_browser|web[\s_-]?view|preview\s+url|https?:\/\/)/i.test(fullText);
        const isFile = /(write_to_file|replace_file_content|apply\s+diff|save\s+file)/i.test(fullText);
        const isScript = /^(?:.*[\\/])?(?:python|python3|py|node|bash|sh|zsh|powershell|pwsh|cmd|ruby|perl|php)(?:\.exe)?(?:\s+|$)/i.test(commandLine) ||
                         /\.(?:py|js|mjs|cjs|ts|sh|bash|bat|cmd|ps1|rb|pl|php|lua)(?:\s|$|[?&"'])/i.test(commandLine);

        let category = 'consoleCommands';
        if (isWeb) category = 'webViews';
        else if (isFile) category = 'fileEdits';
        else if (isScript) category = 'scriptExecution';

        const types = settings.types || {};
        if (types[category]) {
            console.log(JSON.stringify({ decision: 'allow', reason: 'Auto-accepted category: ' + category }));
        } else {
            console.log(JSON.stringify({ decision: 'ask', reason: 'Category ' + category + ' requires confirmation.' }));
        }
    } catch (e) {
        console.log(JSON.stringify({ decision: 'ask', reason: 'Error in autoaccept gate: ' + e.message }));
    }
});
