// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJ-BYmdtfe6nwAjVxdKWDYO_u2EXfHyY',
    appId: '1:421464515774:android:5ec021e3415c1450712aef',
    messagingSenderId: '421464515774',
    projectId: 'stream-phone-cam',
    storageBucket: 'stream-phone-cam.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKCvFJunWMAL1oENBr-kt_Z2NfGGBxDw',
    appId: '1:421464515774:ios:a30dad609274327e712aef',
    messagingSenderId: '421464515774',
    projectId: 'stream-phone-cam',
    storageBucket: 'stream-phone-cam.firebasestorage.app',
    androidClientId: '421464515774-qfkavf3node5cufk4tu7tpr47k74fi84.apps.googleusercontent.com',
    iosClientId: '421464515774-hio994d1r89p2he2vtm90l28c5j88ed6.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamPhoneCam',
  );
}
